-- SECTION 3 AND SECTION 4 
-- TO KNOW DATABASES IN MYSQL
SHOW DATABASES;
--- TO CREATE DB 
CREATE DATABASE CATS;
--USE THE CATS DB
USE CATS;
-- TO KNOW CURRENT DB NAME
SELECT DATABASE();
-- TO CREATE TABLES IN CATS
	-- WITH NAME,BREED,AGE
CREATE TABLE DETAILS(NAME VARCHAR(30),BREED VARCHAR(30),AGE INT);
-- TO THE ATTRIBUTES AND DATA TYPES
DESC DETAILS;
	-- OR
SHOW COLUMNS FROM DETAILS;
-- INSERT DATA TO THE TABLE USIGN MULTPLE INSERTION
INSERT INTO DETAILS(NAME,BREED,AGE) 
	VALUES("Blue","Scottish Fold",1),
			("Rocket","Persian",3),
			("Monty","Tabby",10);
-- TO SEE THE TABLE WITH DETAILS SUING * ( * MEANS GIVES ALL COLUMNS)
SELECT * FROM DETAILS
-- TO KNOW THE TABLES IN THE CATS DB
SHOW TABLES;
-- TO DELETE THE TABLE 
DROP TABLE DETAILS;
-- IF WE ENTER NAME AS 50 LENGTH IT GIVES WARNING
	-- TO SEE THAT WARNING
SHOW WARNINGS;
-- TO INSERT ONLY NAME 
INSERT INTO DETAILS(NAME) VALUES("MONTYY"); -- ANOTHER VALUES IS NULL
-- ANOTHER WAY TO INSERT ONLY NULL VALUES
INSERT INTO DETAILS() VALUES();

-- CREATE ANOTHER TABLE WITH NOT NULL VALUES
CREATE TABLE cats2(name VARCHAR(100) NOT NULL,age  INT NOT NULL); 
--- CREATE A TALBE WITH DEFAULT VALUES
CREATE TABLE cats3(name VARCHAR(100) DEFAULT 'unnamed',age  INT DEFAULT 99); 
--ADD PRIMARY KEY
CREATE TABLE cats4(ID INT NOT NULL,name VARCHAR(100) NOT NULL,age  INT NOT NULL,PRIMARY KEY(ID));

--  ASSIGNMENT 1
/*
		Define an Employees table, with the following fields:
		id - number(automatically increments), mandatory, primary key
		last_name - text, mandatory
		first_name - text, mandatory
		middle_name - text, not mandatory
		age - number mandatory
		current_status - text, mandatory, defaults to 'employed'
*/
CREATE TABLE employees (
    id INT NOT NULL AUTO_INCREMENT,
    last_name VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    age INTEGER NOT NULL,
    current_status VARCHAR(100) NOT NULL DEFAULT 'employed',
    PRIMARY KEY (id)
);