-- SECTION 10
-- REVISITING DATA TYPES
DROP DATABASE IF EXISTS DOMESTICATED_MAMMALS;
CREATE DATABASE DOMESTICATED_MAMMALS;
USE DOMESTICATED_MAMMALS; 

--1.CHAR VS VARCHAR
	CREATE TABLE DOGS (NAME CHAR(5), BREED VARCHAR(10));
	INSERT INTO DOGS (NAME, BREED) VALUES ('BOB', 'BEAGLE');
	INSERT INTO DOGS (NAME, BREED) VALUES ('ROBBY', 'CORGI');
	INSERT INTO DOGS (NAME, BREED) VALUES ('PRINCESS JANE', 'RETRIEVER');
	SELECT * FROM DOGS;
	INSERT INTO DOGS (NAME, BREED) VALUES ('PRINCESS JANE', 'RETRIEVESADFDSAFDASFSAFR');
	SELECT * FROM DOGS;
--2.DECIMAL AND INT
	CREATE TABLE ITEMS(PRICE DECIMAL(5,2));
	INSERT INTO ITEMS(PRICE) VALUES(7);
	INSERT INTO ITEMS(PRICE) VALUES(7987654);
	INSERT INTO ITEMS(PRICE) VALUES(34.88);
	INSERT INTO ITEMS(PRICE) VALUES(298.9999);
	INSERT INTO ITEMS(PRICE) VALUES(1.9999);
	SELECT * FROM ITEMS;
--3.FLOAT AND DOUBLE
	CREATE TABLE COST (PRICE FLOAT);
	INSERT INTO COST(PRICE) VALUES (88.45);
	INSERT INTO COST(PRICE) VALUES (8877.45);
	INSERT INTO COST(PRICE) VALUES (8877665544.45);
	SELECT * FROM COST;
	
	CREATE TABLE COST1 (PRICE DOUBLE);
	INSERT INTO COST1(PRICE) VALUES (88.45);
	INSERT INTO COST1(PRICE) VALUES (8877.45);
	INSERT INTO COST1(PRICE) VALUES (8877665544.45);
	SELECT * FROM COST1;
--4.DATE,TIME AND DATETIME
	CREATE TABLE DATES(NAME VARCHAR(10),BD DATE,TIMING TIME,DOB DATETIME);
	INSERT INTO DATES (NAME,BD,TIMING,DOB) VALUES("KUMAR","1998-05-10","05:30:30","1998-05-10 05:30:30");
	--CURRENT DATE AND TIME
	SELECT CURDATE();
	SELECT CURTIME();
	SELECT NOW(); -- CURRENT DATE AND TIME
	INSERT INTO DATES (NAME,BD,TIMING,DOB) VALUES("KUMAR",CURDATE(),CURTIME(),NOW());
	-- FROMATING DATES
	SELECT DAY(BD) FROM DATES;
	SELECT DAYNAME(BD) FROM DATES;
	SELECT DAYOFWEEK(BD) FROM DATES;
	SELECT DAYOFYEAR(BD) FROM DATES;
	SELECT DAYOFYEAR(TIMING) FROM DATES; -- NULL PRINTS 
	--ANOTHER FORMAT
	--APRIL 21ST 2019
	--CONCAT(MONTHNAME(BD)," ",DAY(BD)," ",YEAR(BD));
	SELECT CONCAT(MONTHNAME(BD)," ",DAY(BD)," ",YEAR(BD)) FROM DATES;
	--DATE_FROMAT
	SELECT DATE_FORMAT(DOB,"%W-%M-%Y") FROM DATES;
	--DATE MATH
	SELECT DATEDIFF(NOW(),BD) FROM DATES;
	
-- TIMESTAMP
	CREATE TABLE TIMESTAMPS(NAME VARCHAR(20),CREATE_AT TIMESTAMP DEFAULT NOW());
	INSERT INTO TIMESTAMPS (NAME) VALUES("MEDARI");
	SELECT * FROM TIMESTAMPS;
	SELECT * FROM TIMESTAMPS ORDER BY CREATE_AT DESC;
	
	CREATE TABLE comments2 (content VARCHAR(100),changed_at TIMESTAMP DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP);
	INSERT INTO comments2 (content) VALUES('dasdasdasd');
	INSERT INTO comments2 (content) VALUES('lololololo');
	INSERT INTO comments2 (content) VALUES('I LIKE CATS AND DOGS');
	UPDATE comments2 SET content='THIS IS NOT GIBBERISH' WHERE content='dasdasdasd';
	SELECT * FROM comments2;
	
--ASSIGNMENT - 1
		/*1.
			CREATE TABLE inventory (
			item_name ____________,
			price ________________,
			quantity _____________
			);
		*/
		CREATE TABLE inventory (
			item_name VARCHAR(10),
			price DECIMAL(8,2),
			quantity INT);
	
	--2.PRINT OUT THE CURRENT TIME
		SELECT CURTIME();
	--3.PRINT OUT THE CURRENT DATE (BUT NOT TIME)
		SELECT CURDATE();
	--4.PRINT OUT THE CURRENT DAY OF THE WEEK -->(THE NUMBER)
		SELECT DAYOFWEEK(CURDATE());
	--5.PRINT OUT THE CURRENT DAY OF THE WEEK -->(THE DAY NAME)
		SELECT DAYNAME(CURDATE());
	--6.PRINT OUT THE CURRENT DAY AND TIME USING THIS FORMAT: MM/DD/YYYY
		SELECT DATE_FORMAT(NOW(),"%m/%d/%Y");
	--7.Print out the current day and time using this format: January 2nd at 3:15 --> April 1st at 10:18
		SELECT DATE_FORMAT(NOW(),CONCAT("%M %D ","at ","%H:%i"));
	/*
		CREATE A TWEETS TABLE THAT STORES:
		THE TWEET CONTENT
		A USERNAME
		TIME IT WAS CREATED
	*/
	CREATE TABLE TWEETS(CONTENT VARCHAR(140),USERNAME VARCHAR(20),CREATED_AT TIMESTAMP DEFAULT NOW());
	INSERT INTO TWEETS (CONTENT, USERNAME) VALUES('THIS IS MY FIRST TWEET', 'COLTSCAT');
	SELECT * FROM TWEETS;
	INSERT INTO TWEETS (CONTENT, USERNAME) VALUES('THIS IS MY SECOND TWEET', 'COLTSCAT');
	SELECT * FROM TWEETS;
